

services:
  nestapp:
    container_name: nestapp
    image: francescoxx/nestapp:1.0.0
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db 
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
    command: npm run start
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
        interval: 10s
        retries: 5
        start_period: 30s
        timeout: 10s    

  postgres_admin:
    image: dpage/pgadmin4:4.28
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.de
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
    volumes:
        - ./db/servers.json:/pgadmin4/servers.json

volumes:
  pgdata: {}
